### ISSUE TITLE
Path name conflict for `version.rb` in isodoc-i18n

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc-i18n#7]
In isodoc-i18n the version is defined in lib/isodoc/version.rb:
https://github.com/metanorma/isodoc-i18n/blob/main/lib/isodoc/version.rb

But in isodoc, the version is also defined under lib/isodoc/version.rb:
https://github.com/metanorma/isodoc/blob/main/lib/isodoc/version.rb

When Ruby loads a file via `require`, it only loads each path once. When Ruby loads the lib/isodoc/version.rb file from isodoc-i18n first, it will not load the real isodoc's lib/isodoc/version.rb. This causes isodoc to not have a version if isodoc-18n is first loaded.

So there are two fixes:
* [x] https://github.com/metanorma/isodoc/pull/453
* [x] #8

**Comment by ronaldtse** [comment]
Done, confirm fixed. Thanks!

**Comment by opoudjis** [comment]
Same issue has turned up in isodoc invocation of relaton-render being ignored by downstream invocations overwriting it.
